title: "Tailin Wu Lab"

menuPages:
  - {
      name: "Home",
      url: "/",
      isIndexHeader: false,
      isNavbar: true,
      isFooter: true,
    }
  - {
      name: "Publications",
      url: "/publications",
      isIndexHeader: true,
      isNavbar: true,
      isFooter: true,
    }
  - {
      name: "Talks",
      url: "/talks",
      isIndexHeader: true,
      isNavbar: true,
      isFooter: true,
    }
  - {
      name: "News",
      url: "/news",
      isIndexHeader: true,
      isNavbar: true,
      isFooter: true,
    }
  - {
      name: "People",
      url: "/people",
      isIndexHeader: true,
      isNavbar: true,
      isFooter: true,
    }
  - {
      name: "Opening",
      url: "/opening",
      isIndexHeader: false,
      isNavbar: true,
      isFooter: true,
    }

groupCategories:
  - {
      icon: "flight",
      category: "Principal Investigator",
      label: "principal-investigator",
      members:
        [
          {
            name: "Tailin Wu",
            pic: "tailinwu.png",
            hasMemoji: true,
            searchInterests:
              [
                "AI for scientific simulation",
                "AI for scientific control and design",
                "AI for scientific discovery",
              ],
            socialLinks:
              [
                { icon: "fa-solid fa-user", link: "http://tailin.org" },
                {
                  icon: "fab fa-github",
                  link: "https://github.com/tailintalent",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/tailin_wu",
                },
                {
                  icon: "fab fa-google",
                  link: "https://scholar.google.com/citations?hl=en&user=axv_UT0AAAAJ&view_op=list_works&sortby=pubdate",
                },
              ],
          },
        ],
    }
  - {
      icon: "airplane_ticket",
      category: "Postdocs and Research Scientists",
      label: "postdocs-and-research-scientists",
      members:
        [
          {
            name: "Long Wei",
            pic: "longwei.png",
            hasMemoji: true,
            searchInterests: ["Machine Learning", "AI for Science"],
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/LongWeiZJU",
                },
              ],
          },
          {
            name: "Qianyi Chen",
            pic: "qianyichen.png",
            hasMemoji: true,
            searchInterests:
              [
                "Data-driven Physical Simulation",
                "Physics-informed Machine Learning",
              ],
            socialLinks:
              [
                {
                  icon: "fa-solid fa-user",
                  link: "https://chen458438184.wixsite.com/biography",
                },
              ],
          },
        ],
    }
  - { icon: "flight_class", category: "PhD Students", label: "phd-students" }
  - {
      icon: "assignment_ind",
      category: "Research Assistant",
      label: "research-assistant",
      members:
        [
          {
            name: "Wenhao Deng",
            pic: "wenhaodeng.png",
            hasMemoji: true,
            searchInterests:
              ["Language Model", "Information Retrieval", "Agents"],
            socialLinks:
              [
                { icon: "fa-solid fa-user", link: "https://w3nhao.github.io/" },
                { icon: "fab fa-github", link: "https://github.com/w3nhao" },
                { icon: "fab fa-twitter", link: "https://twitter.com/dw3nhao" },
                {
                  icon: "far fa-envelope",
                  link: "mailto:wenhao.deng@foxmail.com",
                },
              ],
          },
          {
            name: "Tian Xia",
            pic: "tianxia.png",
            hasMemoji: true,
            searchInterests: ["material science", "machine learning"],
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/Lunar13737",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/summer_ti37",
                },
                {
                  icon: "far fa-envelope",
                  link: "mailto:xiatian20@westlake.edu.cn",
                },
              ],
          },
          {
            name: "Yi Dai",
            pic: "yidai.png",
            hasMemoji: true,
            socialLinks:
              [
                { icon: "fab fa-github", link: "https://github.com/PascalDai" },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/PascalDai",
                },
              ],
          },
        ],
    }
  - {
      icon: "flight_land",
      category: "Visiting Students",
      label: "visiting-students",
      members:
        [
          {
            name: "Junjie Shan",
            pic: "junjieshan.png",
            hasMemoji: true,
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/JamerryShan",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/junjieshan_",
                },
              ],
          },
          {
            name: "Hongtao Zheng",
            pic: "hongtaozheng.png",
            hasMemoji: true,
            searchInterests: ["PDE Solving", "Uncertainty Quantification"],
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/Zhangtao167",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/zhenghongtao06",
                },
              ],
          },
          {
            name: "Jiaxin Li",
            pic: "jiaxinli.png",
            hasMemoji: true,
            socialLinks:
              [{ icon: "fab fa-github", link: "https://github.com/Jiaxinlia" }],
          },
          {
            name: "Siyuan Li",
            pic: "siyuanli.png",
            hasMemoji: true,
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/liaoyanqing666",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/liaoyanqing6666",
                },
              ],
          },
          {
            name: "Tao Zhang",
            pic: "taozhang.png",
            hasMemoji: true,
            searchInterests:
              ["control theory", "machine learning", "inverse design"],
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/Zhangtao167",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/tozhng979237695",
                },
                {
                  icon: "far fa-envelope",
                  link: "mailto:zhangtao@westlake.edu.cn",
                },
              ],
          },
          {
            name: "Chenglei Yu",
            pic: "chengleiyu.png",
            hasMemoji: true,
            searchInterests:
              ["protein design", "neural network", "physical system"],
            socialLinks:
              [{ icon: "fab fa-github", link: "https://github.com/oYCLo" }],
          },
          {
            name: "Peiyan Hu",
            pic: "peiyanhu.png",
            hasMemoji: true,
            searchInterests: ["AI for PDEs", "Ai for Physics"],
            socialLinks:
              [
                {
                  icon: "far fa-envelope",
                  link: "hupeiyan18@mails.ucas.ac.cn",
                },
              ],
          },
          {
            name: "Rundong He",
            pic: "rundonghe.png",
            hasMemoji: true,
            searchInterests:
              [
                "Uncertainty Estimation",
                "Out-of-Distribution Detection",
                "Robust Weakly-supervised Learning",
              ],
            socialLinks:
              [
                {
                  icon: "fa-solid fa-user",
                  link: "https://rundonghe.github.io",
                },
              ],
          },
          {
            name: "Ruiqi Feng",
            pic: "ruiqifeng.png",
            hasMemoji: true,
            searchInterests: ["AI for scientific"],
            socialLinks:
              [
                {
                  icon: "fa-solid fa-user",
                  link: "https://weenming.github.io",
                },
              ],
          },
          {
            name: "Yixuan Du",
            pic: "yixuandu.png",
            hasMemoji: true,
            searchInterests: ["Graph machine learning", "AI4SCI"],
            socialLinks:
              [
                { icon: "fab fa-github", link: "https://github.com/Duyx5149" },
                {
                  icon: "far fa-envelope",
                  link: "mailto:yixuantu42@gmail.com",
                },
              ],
          },
          {
            name: "Rui Wang",
            pic: "ruiwang.png",
            hasMemoji: true,
            searchInterests: ["AI for science", "AI for communication"],
            socialLinks: [],
          },
        ],
    }
  - {
      icon: "flight_takeoff",
      category: "Alumnus",
      label: "alumnus",
      members:
        [
          {
            name: "Xianfeng Wu",
            pic: "xianfengwu.png",
            hasMemoji: true,
            searchInterests:
              ["3D Vision", "AI4Science", "Trustworthy Machine Learning"],
            socialLinks:
              [
                {
                  icon: "fa-solid fa-user",
                  link: "https://maradona10wxf.github.io/",
                },
                {
                  icon: "fab fa-github",
                  link: "https://github.com/XianfengWu01",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/xianfengwu10",
                },
                {
                  icon: "far fa-envelope",
                  link: "mailto:wxf20011228@gmail.com",
                },
              ],
          },
          {
            name: "Zhuohao Ni",
            pic: "zhuohaoni.png",
            hasMemoji: true,
            socialLinks:
              [
                { icon: "fab fa-github", link: "https://github.com/ZhuohaoNi" },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/ppppnnnni",
                },
              ],
          },
          {
            name: "Xiang Zheng",
            pic: "xiangzheng.png",
            hasMemoji: true,
            searchInterests: ["Physics Simulation & Prediction"],
            socialLinks:
              [
                {
                  icon: "fab fa-github",
                  link: "https://github.com/Ashleyhoho",
                },
                {
                  icon: "fab fa-twitter",
                  link: "https://twitter.com/hahaheihei79447",
                },
                { icon: "far fa-envelope", link: "mailto:1793434271@qq.com" },
              ],
          },
          {
            name: "Yu Wang",
            pic: "yuwang.png",
            hasMemoji: false,
            searchInterests:
              [
                "Retrosynthesis Prediction",
                "Protein-protein Interaction Design",
                "Drug Discovery",
              ],
            socialLinks:
              [{ icon: "fab fa-github", link: "https://github.com/wangyu-sd" }],
          },
        ],
    }
    #undergraduate
  - {
      icon: "group",
      category: "Undergraduate",
      label: "undergraduate",
      members:
        [
          { name: "Zebang Wu", pic: "zebangwu.png", hasMemoji: true },
          { name: "Yixian Jiang", pic: "yixianjiang.png", hasMemoji: true },
        ],
    }
  - {
      icon: "face",
      category: "Collaborator",
      label: "collaborator",
      members:
        [
          {
            name: "Haixin Wang",
            pic: "haixinwang.png",
            hasMemoji: true,
            searchInterests: ["Deep Learning", "AI for Science"],
          },
          { name: "Qianru Zhang", pic: "qianruzhang.png", hasMemoji: true },
        ],
    }

menuItems:
  talks: "Talks"
  people: "People"
  publications: "Publications"
  news: "News"
  opening: "Opening"
  join_us: "Join Us"
  about_our_team: "About Our Team"
  invited_talks: "Invited Talk"
  featured_talks: "Featured talks"
  other_talks: "Other talks"

our_team_subtitle: "The Journey is the Reward"

mainpageContent:
  title: "Our lab mission is to"
  subtitles: ["solve important AI + Science problems", "open new frontiers"]
  quote: "The time is now for it to be okay to be great. People in this world shun people for being great. For being a bright color."
